version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:9.9.7-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=ad
    depends_on:
      - postgres
    volumes:
      - sonarqube_conf:/var/sonarqube/conf
      - sonarqube_data:/var/sonarqube/data
      - sonarqube_extensions:/var/sonarqube/extensions
      - sonarqube_logs:/var/sonarqube/logs
      - sonarqube_temp:/var/sonarqube/temp

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
