version: "3"

services:

  reverse_proxy:
    image: nginx:1.26.2-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot:/certbot
    networks:
      - sonar-net

networks:
    sonar-net:
      driver: bridge
